config/routes.rb
Rails.application.routes.draw do
  resources :stores
  resources :pets
  resources :users



  namespace :owner do
  resources :stores
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'



end

app/models/pets.rb
class Pet < ActiveRecord::Base
  belongs_to :store
end

app/models/stores.rb
class Store < ActiveRecord::Base
  has_many :pets 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stores
  has_secure_password
  validates :password, :length => {:minimum => 6 , :message => "Must 6 characters or more"}
validates :username, presence: true,
                     uniqueness: true

enum role: %w(default owner)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def current_user
  @user ||= User.find(session[:user_id]) if session[:user_id]
end

def current_owner?
  current_user && current_user.owner?
end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def show
  end

  def new
  end

  def create
  end

  def update
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username:params[:session][:username])
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def new
    @store= Store.new
  end

  def create
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user= User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user= User.new(user_params)
    if @user.save
      redirect_to @user
    else
      flash[:error]= "Those are not valid inputs"
      render :new
    end
  end

  def update
  end


private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stores/show.html.erb
<p></p>

app/views/users/new.html.erb
<h1>Create an Account</h1>
<%= flash.now[:error] %>
<br></br>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br></br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>Hello, <%=@user.username%></h1>
<h2>Stores:</h2>


<%= link_to "Create New Store", new_store_path %>